resources:
  repositories:
  - repository: templates
    type: git
    name: pinc/azure-pipeline-templates
    ref: refs/heads/master

jobs:
- job: docker
  steps:
  - template: docker-build-push.yml@templates
    parameters:
      RepoOrg: 'phs'
